name: Android Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build GitHub APK
        run: ./gradlew assembleGithubRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: stillshelf-github-apk
          path: app/build/outputs/apk/github/release/*.apk
